export const PAYMENT_STATUS = {
    PENDING:'PENDING',
    COMPLETED:'COMPLETED',
    FAILED:'FAILED',
    BALANCEDUE:'BALANCE DUE',
}

export const PAYMENT_METHOD ={
    CASH :'CASH',
    ONLINE : 'ONLINE',
    CHEQUE : 'CHEQUE',
    LOAN : 'LOAN',
}