export const MODULES = {
  AUTH: 'AUTH',
  USER: 'USER',
  STAFF: 'STAFF',
  PAYMENT: 'PAYMENT',
  WORKS: 'WORKS',
  CUSTOMER: 'CUSTOMER',
  REPORT: 'REPORT',
  DASHBOARD: 'DASHBOARD',
  FORMFEILDS: 'FORM-FIELDS',
  BACKUP: 'BACKUP',
  SERVICES: 'SERVICES',
};
